services:
  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - '5173:80'
    depends_on:
      - server
    environment:
      - NODE_ENV=production # for optimization
    #restart: always

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - '3000:3000'
      - '8000:8000' # for websocket
    depends_on:
      - redis
    env_file:
      - ./server/.env.production
    environment:
      - NODE_ENV=production
    restart: always

  redis:
    image: 'redis/redis-stack-server:latest'
    ports:
      - '6379:6379'
    restart: always
    volumes:
      - 'redis_data:/data'
volumes:
  redis_data:
