version: '3'

services:
  client:
    build: ./client
    ports:
      - '3000:3000'
    depends_on:
      - server
    environment:
      - NODE_ENV=production
    restart: always

  server:
    build: ./server
    ports:
      - '8000:8000'
    depends_on:
      - redis
    environment:
      - NODE_ENV=production
      - DATABASE_URL=redis://redis:6379
    restart: always

  redis:
    image: 'redis/redis-stack-server:latest'
    ports:
      - '6379:6379'
    restart: always
    volumes:
      - 'redis-data:/data'
